import {
  COLORS,
  FontSize,
  FontWeight,
  SpacingValues,
  ScreenPadding,
  ComponentSpacing,
} from "@/constants/theme";
import {
  Dimensions,
  Platform,
  StyleSheet,
} from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: ScreenPadding.vertical,
    paddingTop:
      Platform.OS === "ios" ? 10 : ScreenPadding.vertical,
    paddingBottom: ScreenPadding.vertical,
    backgroundColor: COLORS.background,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    position: "relative",
  },
  headerTitle: {
    fontSize: 28,
    fontFamily: "JetBrainsMono-Medium",
    color: COLORS.text,
    fontWeight: FontWeight.bold,
    textAlign: "center",
    flex: 1,
    textShadowColor: COLORS.primary,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  logoutButton: {
    position: "absolute",
    right: ScreenPadding.vertical,
    padding: SpacingValues.sm,
    borderRadius: SpacingValues.sm,
    backgroundColor: COLORS.surface,
  },
  filterSection: {
    paddingHorizontal: ScreenPadding.vertical,
    paddingVertical: SpacingValues.base,
    alignItems: "center",
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
    paddingHorizontal: ScreenPadding.vertical,
    paddingVertical: ComponentSpacing.buttonPaddingVertical,
    borderRadius: 25,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  filterButtonText: {
    color: COLORS.background,
    fontSize: FontSize.body,
    fontWeight: FontWeight.semibold,
    marginLeft: ComponentSpacing.iconMargin,
  },
  filterCountBadge: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    paddingHorizontal: SpacingValues.sm,
    paddingVertical: SpacingValues.xs,
    marginLeft: SpacingValues.md,
    minWidth: SpacingValues.lg,
    alignItems: "center",
  },
  filterCountText: {
    color: COLORS.primary,
    fontSize: FontSize.caption,
    fontWeight: FontWeight.bold,
  },
  activeFiltersContainer: {
    paddingHorizontal: ScreenPadding.vertical,
    paddingBottom: SpacingValues.base,
    alignItems: "center",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    paddingHorizontal:
      ComponentSpacing.buttonPaddingHorizontal,
    paddingVertical: SpacingValues.sm,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    maxWidth: "90%",
  },
  filterChipText: {
    color: COLORS.textMuted,
    fontSize: FontSize.bodySmall,
    flex: 1,
    marginRight: SpacingValues.sm,
  },
  clearFilterButton: {
    backgroundColor: COLORS.border,
    borderRadius: 12,
    padding: SpacingValues.xs,
  },
  flatListContent: {
    paddingHorizontal: ScreenPadding.vertical,
    paddingBottom: 100,
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    paddingHorizontal: ScreenPadding.vertical,
  },
  emptyStateText: {
    color: COLORS.textMuted,
    fontSize: FontSize.body,
    textAlign: "center",
    marginTop: SpacingValues.base,
    lineHeight: 24,
  },
  sectionContainer: {
    marginTop: SpacingValues.xl,
    paddingVertical: ScreenPadding.vertical,
    borderTopWidth: 1,
    borderTopColor: COLORS.surface,
  },
  sectionHeader: {
    color: COLORS.text,
    fontSize: FontSize.h2,
    fontWeight: FontWeight.bold,
    marginBottom: SpacingValues.base,
    textAlign: "center",
  },
  storiesContainer: {
    paddingVertical: SpacingValues.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.surface,
  },
  storyWrapper: {
    alignItems: "center",
    marginHorizontal: SpacingValues.sm,
    width: 72,
  },
  storyRing: {
    width: 68,
    height: 68,
    borderRadius: 34,
    padding: 2,
    backgroundColor: COLORS.background,
    borderWidth: 2,
    borderColor: COLORS.primary,
    marginBottom: SpacingValues.xs,
  },
  noStory: {
    borderColor: COLORS.textMuted,
  },
  storyAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: COLORS.background,
  },
  storyUsername: {
    fontSize: FontSize.caption,
    color: COLORS.text,
    textAlign: "center",
  },
  post: {
    marginBottom: SpacingValues.base,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: SpacingValues.md,
  },
  postHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  postAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: SpacingValues.sm,
  },
  postUsername: {
    fontSize: FontSize.bodySmall,
    fontWeight: FontWeight.semibold,
    color: COLORS.text,
  },
  postImage: {
    width: width,
    height: width,
  },
  postActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SpacingValues.md,
    paddingVertical: SpacingValues.md,
  },
  postActionsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SpacingValues.base,
  },
  postInfo: {
    paddingHorizontal: SpacingValues.md,
  },
  likesText: {
    fontSize: FontSize.bodySmall,
    fontWeight: FontWeight.semibold,
    color: COLORS.text,
    marginBottom: 6,
  },
  captionContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 6,
  },
  captionUsername: {
    fontSize: FontSize.bodySmall,
    fontWeight: FontWeight.semibold,
    color: COLORS.text,
    marginRight: 6,
  },
  captionText: {
    fontSize: FontSize.bodySmall,
    color: COLORS.text,
    flex: 1,
  },
  commentsText: {
    fontSize: FontSize.bodySmall,
    color: COLORS.textMuted,
    marginBottom: SpacingValues.xs,
  },
  timeAgo: {
    fontSize: FontSize.caption,
    color: COLORS.textMuted,
    marginBottom: SpacingValues.sm,
  },
  modalContainer: {
    backgroundColor: COLORS.background,
    marginBottom: Platform.OS === "ios" ? 44 : 0,
    flex: 1,
    marginTop: Platform.OS === "ios" ? 44 : 0,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SpacingValues.base,
    height: 56,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.surface,
  },
  modalTitle: {
    color: COLORS.text,
    fontSize: FontSize.body,
    fontWeight: FontWeight.semibold,
  },
  commentsList: {
    flex: 1,
  },
  commentContainer: {
    flexDirection: "row",
    paddingHorizontal: SpacingValues.base,
    paddingVertical: SpacingValues.md,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.surface,
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: SpacingValues.md,
  },
  commentContent: {
    flex: 1,
  },
  commentUsername: {
    color: COLORS.text,
    fontWeight: FontWeight.medium,
    marginBottom: SpacingValues.xs,
  },
  commentText: {
    color: COLORS.text,
    fontSize: FontSize.bodySmall,
    lineHeight: 20,
  },
  commentTime: {
    color: COLORS.textMuted,
    fontSize: FontSize.caption,
    marginTop: SpacingValues.xs,
  },
  commentInput: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SpacingValues.base,
    paddingVertical: SpacingValues.md,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.surface,
    backgroundColor: COLORS.background,
  },
  input: {
    flex: 1,
    color: COLORS.text,
    paddingVertical: SpacingValues.sm,
    paddingHorizontal: SpacingValues.base,
    marginRight: SpacingValues.md,
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    fontSize: FontSize.bodySmall,
  },
  postButton: {
    color: COLORS.primary,
    fontWeight: FontWeight.semibold,
    fontSize: FontSize.bodySmall,
  },
  postButtonDisabled: {
    opacity: 0.5,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
});
